version: '2'
services:
  codeforfuture-app:
    image: codeforfuture
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://codeforfuture-mariadb:3306/codeforfuture
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://codeforfuture-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://codeforfuture-elasticsearch:9200
    ports:
      - 8080:8080
  codeforfuture-mariadb:
    extends:
      file: mariadb.yml
      service: codeforfuture-mariadb
  codeforfuture-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: codeforfuture-elasticsearch
